create table estoque (
     id bigint generated by default as identity primary key,
     quantidade_disponivel integer not null,
     criado_em timestamp not null,
     atualizado_em timestamp
);

insert into estoque (quantidade_disponivel, criado_em, atualizado_em) values (100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into estoque (quantidade_disponivel, criado_em, atualizado_em) values (75, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into estoque (quantidade_disponivel, criado_em, atualizado_em) values (50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into estoque (quantidade_disponivel, criado_em, atualizado_em) values (30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into estoque (quantidade_disponivel, criado_em, atualizado_em) values (20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into estoque (quantidade_disponivel, criado_em, atualizado_em) values (0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into estoque (quantidade_disponivel, criado_em, atualizado_em) values (200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into estoque (quantidade_disponivel, criado_em, atualizado_em) values (150, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into estoque (quantidade_disponivel, criado_em, atualizado_em) values (10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into estoque (quantidade_disponivel, criado_em, atualizado_em) values (5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
